# ENTRY SCHEMA
 
# --- !Ups
 
CREATE TABLE ENTRIES (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(128) NOT NULL,
    CONTENT TEXT,
    ADDED TIMESTAMP,
    UPDATED TIMESTAMP,
    RATING INT,
    USER_ID BIGINT,
    PRIMARY KEY (ID),
    INDEX (TITLE),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
) ENGINE=InnoDB;

CREATE TABLE TAGS(
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(128) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE INDEX (NAME)
) ENGINE=InnoDB;

CREATE TABLE ENTRY_TAG (
    ENTRY_ID BIGINT UNSIGNED NOT NULL,
    TAG_ID INT UNSIGNED NOT NULL,
    PRIMARY KEY (ENTRY_ID, TAG_ID),
    INDEX (TAG_ID),
    FOREIGN KEY (ENTRY_ID) REFERENCES ENTRIES(ID),
    FOREIGN KEY (TAG_ID) REFERENCES TAGS(ID)
) ENGINE=InnoDB;

CREATE TABLE SOURCES(
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(128) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE INDEX (NAME)
) ENGINE=InnoDB;

CREATE TABLE ENTRY_SOURCE (
    ENTRY_ID BIGINT UNSIGNED NOT NULL,
    SOURCE_ID INT UNSIGNED NOT NULL,
    PRIMARY KEY (ENTRY_ID, SOURCE_ID),
    INDEX (SOURCE_ID),
    FOREIGN KEY (ENTRY_ID) REFERENCES ENTRIES(ID),
    FOREIGN KEY (SOURCE_ID) REFERENCES SOURCES(ID)
) ENGINE=InnoDB;

# --- !Downs 

DROP TABLE ENTRIES IF EXISTS;
DROP TABLE TAGS IF EXISTS;
DROP TABLE ENTRY_TAG IF EXISTS;
DROP TABLE SOURCES IF EXISTS;
DROP TABLE ENTRY_SOURCE IF EXISTS;
