# ENTRY USER
 
# --- !Ups
 
CREATE TABLE USERS(
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(128) NOT NULL,
    EMAIL VARCHAR(128) NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL,
    REGISTERDATE TIMESTAMP,
    PRIMARY KEY (ID),
    INDEX (EMAIL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


# --- !Downs 

DROP TABLE USERS IF EXISTS;

