# ENTRY SCHEMA
 
# --- !Ups
 
CREATE TABLE ENTRIES (
    ID INT  NOT NULL AUTO_INCREMENT,
    HEADWORD VARCHAR(128) NOT NULL,
    CONTEXT TEXT,
    ADDED TIMESTAMP,
    UPDATED TIMESTAMP,
    RATING INT,
    SOUND VARCHAR(128),
    PRONUNCIATION VARCHAR(128),
    WORDCLASS VARCHAR(12),
    USER_ID INT,
    PRIMARY KEY (ID),
    INDEX (HEADWORD),
    FULLTEXT (WORDCLASS),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TAGS(
    ID INT  NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(128) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE INDEX (NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ENTRY_TAG (
    ENTRY_ID INT  NOT NULL,
    TAG_ID INT  NOT NULL,
    PRIMARY KEY (ENTRY_ID, TAG_ID),
    INDEX (TAG_ID),
    FOREIGN KEY (ENTRY_ID) REFERENCES ENTRIES(ID),
    FOREIGN KEY (TAG_ID) REFERENCES TAGS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE SOURCES(
    ID INT  NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(128) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE INDEX (NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ENTRY_SOURCE (
    ENTRY_ID INT  NOT NULL,
    SOURCE_ID INT  NOT NULL,
    PRIMARY KEY (ENTRY_ID, SOURCE_ID),
    INDEX (SOURCE_ID),
    FOREIGN KEY (ENTRY_ID) REFERENCES ENTRIES(ID),
    FOREIGN KEY (SOURCE_ID) REFERENCES SOURCES(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# --- !Downs 

DROP TABLE ENTRIES IF EXISTS;
DROP TABLE TAGS IF EXISTS;
DROP TABLE ENTRY_TAG IF EXISTS;
DROP TABLE SOURCES IF EXISTS;
DROP TABLE ENTRY_SOURCE IF EXISTS;
