# ENTRY SCHEMA

# --- !Ups

CREATE TABLE DEFINITIONS (
    ID INT NOT NULL AUTO_INCREMENT,
    ENTRY VARCHAR(128) NOT NULL,
    DEFINITION TEXT NOT NULL,
    FORMAT VARCHAR(128),
    SOURCE VARCHAR(256),
    ENTRY_ID INT ,
    PRIMARY KEY (ID),
    INDEX (ENTRY),
    FOREIGN KEY (ENTRY_ID) REFERENCES ENTRIES(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# --- !Downs

DROP TABLE DEFINITIONS IF EXISTS;
